Ref #3218 - Add the LGPL mySQL JDBC driver in studio distribution
Qualif error in trunk come from the unwanted commit of Elodie of the mysql-connector_fake.jar, that cause the !FakeJarException instead of using the true mysql connector from tomcat/lib.

Also add a java version checking before Driver switch to prevent the !NoClassDefFoundError on java.sql.NClob (and just let the !NoClassDefFoundError for com.mysql.jdbc.Driver).

Former-commit-id: 60a65784623fc249f63c188f3c290f190c36c447
Former-commit-id: 7b3ea6124b1b9baaaee3c7f479ab8e2f61f1e936
Former-commit-id: 878640a8603921e249313206d4014e346728b977
Former-commit-id: d6600c2abd3f9ad221db6c5b1665751bdfd2185f