Ref #3218 - Add the LGPL mySQL JDBC driver in studio distribution
Qualif error in trunk come from the unwanted commit of Elodie of the mysql-connector_fake.jar, that cause the !FakeJarException instead of using the true mysql connector from tomcat/lib.

Also add a java version checking before Driver switch to prevent the !NoClassDefFoundError on java.sql.NClob (and just let the !NoClassDefFoundError for com.mysql.jdbc.Driver).

Former-commit-id: c874dc76e4405eb3bef71f6731f148dff63854ad
Former-commit-id: 613ffb1979a5b78ff4b55ae9ebd0353d85d7d7ec
Former-commit-id: 7cf45533646671a39193abeceaa6d8bf8bba93f9
Former-commit-id: c5cb6a9123577190d411933422682f2275c38e1f